[package]
name = "brief-parser"
version = "0.1.0"
edition = "2024"

[dependencies]
brief-ast = { path = "../brief-ast" }
brief-lexer = { path = "../brief-lexer" }
brief-diagnostic = { path = "../brief-diagnostic" }
